cookie:
  expiry_days: 30
  key: some_signature_key # Must be a string
  name: some_cookie_name
credentials:
  usernames:
    ho.ko:
      email: ho.ko@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: ho.ko
      last_name: 
      logged_in: False # Will be managed automatically
      password: '123' # Will be hashed automatically
      roles: # Optional
      - admin
      - editor
      - viewer
    cliente1:
      email: cliente1@gmail.com
      failed_login_attempts: 0 # Will be managed automatically
      first_name: cliente
      last_name: fulano
      logged_in: False # Will be managed automatically
      password: '123' # Will be hashed automatically
      roles: # Optional
      - viewer
